def build_email_html(weather_data, news_list, finance_data):
    """Build HTML email from data"""

    html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <style>
            body {{
                font-family: Arial, sans-serif;
                max-width: 600px;
                margin: 0 auto;
                padding: 20px;
                background-color: #f5f5f5;
            }}
            .container {{
                background-color: white;
                padding: 30px;
                border-radius: 10px;
            }}
            h1 {{
                color: #0066cc;
                border-bottom: 3px solid #0066cc;
                padding-bottom: 10px;
            }}
            h2 {{
                color: #333;
                margin-top: 30px;
            }}
            .news-item {{
                margin: 15px 0;
                padding: 10px;
                background-color: #f9f9f9;
                border-left: 4px solid #0066cc;
            }}
            a {{
                color: #0066cc;
                text-decoration: none;
            }}
        </style>
    </head>
    <body>
        <div class="container">
            <h1>Daily Digest</h1>
            <p style="color: #666;">Your personalized daily update</p>

            <h2>Weather</h2>
            <p><strong>Temperature:</strong> {weather_data.get('temp', 'N/A')}°C</p>
            <p><strong>Condition:</strong> {weather_data.get('condition', 'N/A')}</p>

            <h2>Top News</h2>
            {''.join([f'<div class="news-item"><strong>{source}:</strong> <a href="{link}">{title}</a></div>' for source, title, link in news_list[:5]])}

            <h2>Finance</h2>
            <p><strong>Bitcoin:</strong> ${finance_data.get('btc', 'N/A')}</p>

            <hr style="margin-top: 40px; border: none; border-top: 1px solid #ddd;">
            <p style="color: #999; font-size: 12px; text-align: center;">
                Generated by Daily Digest Bot
            </p>
        </div>
    </body>
    </html>
    """

    return html